# Generated by Django 6.0.4 on 2026-04-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название региона')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра (м/с)')),
                ('humidity', models.IntegerField(verbose_name='Влажность (%)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура (°C)')),
                ('coordinate', models.CharField(max_length=70, null=True, verbose_name='Координаты')),
                ('event_type', models.CharField(choices=[('storm', 'Шторм'), ('thunder', 'Гроза'), ('snow', 'Снег'), ('heat', 'Жара')], max_length=20)),
                ('danger_level', models.IntegerField(choices=[(1, 'Зелёный (низкий)'), (2, 'Жёлтый (средний)'), (3, 'Оранжевый (высокий)'), (4, 'Красный (опасный)')])),
                ('status', models.CharField(choices=[('active', 'Активное'), ('finished', 'Завершено')], default='active', max_length=10)),
                ('radius_km', models.FloatField(help_text='Радиус действия в км')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather_danger.region', verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='ImageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='weather_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='weather_danger.weatherevent')),
            ],
        ),
    ]
