# Generated by Django 6.0.4 on 2026-04-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_danger', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebutton',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weather_images/'),
        ),
    ]
