# Generated by Django 6.0.4 on 2026-05-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_danger', '0005_remove_profile_bio_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reports_count',
        ),
    ]
