# Generated by Django 6.0.4 on 2026-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_danger', '0007_rename_location_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
