# Generated by Django 6.0.4 on 2026-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_danger', '0009_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherevent',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='weatherevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='weatherevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='weatherevent',
            name='event_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('fire', 'Fire'), ('hurricane', 'Hurricane'), ('heavy_rain', 'Heavy Rain'), ('extreme_temp', 'Extreme Heat / Frost'), ('thunderstorm', 'Thunderstorm'), ('landslide', 'Landslide')], max_length=20),
        ),
    ]
