# Generated by Django 6.0.4 on 2026-05-11 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_danger', '0010_remove_weatherevent_coordinate_weatherevent_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherevent',
            name='region',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weather_danger.weatherevent'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weatherevent',
            name='danger_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10, verbose_name='Уровень опасности'),
        ),
        migrations.AlterField(
            model_name='weatherevent',
            name='event_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('fire', 'Fire'), ('hurricane', 'Hurricane'), ('heavy_rain', 'Heavy Rain'), ('extreme_temp', 'Extreme Heat / Frost'), ('thunderstorm', 'Thunderstorm'), ('landslide', 'Landslide')], max_length=30, verbose_name='Тип явления'),
        ),
        migrations.AlterField(
            model_name='weatherevent',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Влажность (%)'),
        ),
        migrations.AlterField(
            model_name='weatherevent',
            name='radius_km',
            field=models.PositiveIntegerField(default=1, verbose_name='Радиус опасности (км)'),
        ),
        migrations.AlterField(
            model_name='weatherevent',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('resolved', 'Устранено')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='weatherevent',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость ветра (м/с)'),
        ),
        migrations.DeleteModel(
            name='ImageButton',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
