# Generated by Django 6.0.5 on 2026-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_danger', '0013_safety_platform_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location_text',
            field=models.CharField(blank=True, help_text='Например: 41.3111, 69.2797', max_length=255, verbose_name='Моя геолокация'),
        ),
    ]
