# Generated by Django 6.0.5 on 2026-05-14 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_danger', '0014_alter_comment_location_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('distance_km', models.FloatField(verbose_name='Расстояние, км')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('shown_as_popup', models.BooleanField(default=False, verbose_name='Показано всплывающим окном')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danger_notifications', to='weather_danger.weatherevent', verbose_name='Катаклизм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danger_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление об опасности',
                'verbose_name_plural': 'Уведомления об опасности',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
